# Generated by Django 6.0.4 on 2026-04-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_files', models.IntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('duplicate_lines', models.IntegerField(default=0)),
                ('duplication_percentage', models.FloatField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='projects.project')),
            ],
        ),
    ]
