# Generated by Django 6.0.4 on 2026-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='ai_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
