# Generated by Django 6.0.4 on 2026-04-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_analysisresult_ai_suggestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAnalysis',
        ),
    ]
