# Generated by Django 6.0.4 on 2026-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_projectanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
    ]
