# Generated by Django 6.0.4 on 2026-06-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_task_ai_response_task_code_snippet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROJECT_UPLOADED', 'Project Uploaded'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_ANALYZED', 'Project Analyzed'), ('TASK_CREATED', 'Task Created'), ('TASK_ANALYZED', 'Task Analyzed'), ('CODE_FIXED', 'Code Fixed'), ('FILE_OPENED', 'File Opened'), ('FILE_DOWNLOADED', 'File Downloaded')], max_length=100)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.TextField(blank=True)),
                ('status_code', models.IntegerField(default=200)),
                ('message', models.TextField(blank=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
